baseURL: "https://cozyan.github.io"
languageCode: en-us
title: "Yan Liang | æ¢ç°"
copyright: "Â© 2024 cozyan.github.io. All rights reserved."
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
# enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false
enableEmoji: true
# pygmentsUseClasses: true
# mainsections: ["posts"]

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    params:
      homeInfoParams:
        Title: "Cozyan's Canvas"
        Content: >
          Hi! ğŸ‘‹ I'm Cozyan, just a regular person navigating the ups and downs of tech ğŸ–¥ï¸, 
          
          life's rollercoasters, and the ever-twisting world of finance.
          
          At Cozyan's Canvas ğŸ¨, I share my stories and discoveries, 
          
          all served with a dash of humor and a slice of beef ğŸ¥© for relatability ğŸ˜Š.
    menu:
      main:
        - name: About
          url: about
          weight: 1
        - name: Blog
          url: blog
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        # - name: WiKi
        #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/
    
  cn:
    languageName: "ä¸­æ–‡"
    weight: 2
    taxonomies:
      category: CNcategories
      tag: CNtags
      series: CNseries
    params:
      homeInfoParams:
        Title: "Cozyan's Canvas"
        Content: >
          å—¨å—¨å¤§å®¶ï¼ğŸ‘‹ 

          æˆ‘æ˜¯Cozyanï¼Œä¸€ä¸ªæ™®é€šäººï¼Œä¸€è¾¹åœ¨æŠ€æœ¯çš„æ·±å‘é‡Œæ‘¸çˆ¬æ»šæ‰“ ğŸ–¥ï¸ï¼Œä¸€è¾¹åç€ç”Ÿæ´»çš„è¿‡å±±è½¦ ğŸ¢ï¼Œ

          è¿˜é¡ºä¾¿ç„ä¸€çœ¼é‡‘èä¸–ç•Œçš„èŠ±èŠ±ç»¿ç»¿ ğŸ’°ã€‚

          æˆ‘ä¼šåˆ†äº«æˆ‘çš„æ—¥å¸¸ç¢ç¢å¿µå’Œå„ç§å¥‡æ€ªå‘ç°ï¼Œè½»æ¾å¸¦ç‚¹æ²™é›•é£ï¼Œè¿˜ä¼šå¡ç‚¹â€œç¡¬æ ¸å¹²è´§â€ ğŸ¥©ï¼Œ

          å¸Œæœ›èƒ½è®©ä½ çœ‹ç€å¼€å¿ƒåˆè§‰å¾—æœ‰ç‚¹ç”¨ï¼å¿«æ¥ç©å§ï½ğŸ˜Š
    menu:
      main:
        - name: å…³äºæˆ‘
          url: about/
          weight: 1
        - name: åšå®¢
          url: blog/
          weight: 5
        - name: æœç´¢
          url: search/
          weight: 10
        - name: æ ‡ç­¾
          url: cntags
          weight: 10
  
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  # author: Theme PaperMod
  # author: ["Me", "You"] # multiple authors

  browserTitle: "Yan Liang | æ¢ç°"
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  comments: true
  # images: ["images/papermod-cover.png"]

  # profileMode:
  #   enabled: false
  #   title: PaperMod
  #   imageUrl: "#"
  #   imageTitle: my image
  #   # imageWidth: 120
  #   # imageHeight: 120
  #   buttons:
  #     - name: Archives
  #       url: archives
  #     - name: Tags
  #       url: tags


  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/cozyan"
    # - name: Discord
    #   title: Join discord community
    #   url: "https://discord.gg/ahpmTvhVmp"
    - name: X
      title: Share PaperMod on X/Twitter
      url: "https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/adityatelange/hugo-PaperMod&hashtags=Hugo,PaperMod"
    - name: LinkedIn
      title: Message me on LinkedIn
      url: "https://www.linkedin.com/in/gemma-liang/"
    - name: medium
      title: Read my articles on Medium
      url: "https://medium.com/@cozyan"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/cozyan"

  # editPost:
  #   URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  label:
    text: "Home"
    icon: "/assets/images/avatar.png"
    iconHeight: 35

  analytics:
      google:
        id: G-W02F5BM27Q
        SiteVerificationTag: "EZkQ2kjveTiffXyslGKsoz1pnbIR7DTAhatwUQ_kTWo"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
    favicon16x16: "/assets/images/avatar.png"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

  gitalk:
    owner: "cozyan"
    repo: "site-comment-git"
    clientId: "Ov23lims4tKqXdOWGaWV"
    clientSecret: "6828096289e2edc86d49444bad1819cb1e157b6e"

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true